name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm install -g pnpm && pnpm install

    - name: Build the project
      run: pnpm run build

    - name: Move build output to root
      run: |
        mkdir temp-gh-pages
        mv out/renderer/* temp-gh-pages/
        mv temp-gh-pages/* .
        rm -rf temp-gh-pages

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Root directory after moving contents
