name: Electron Build & Release (All Platforms)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install

      - name: Generate Tag
        id: tag
        run: |
          echo "tag=$(git describe --tags --always HEAD)" >> $GITHUB_OUTPUT
      
      - name: Install WiX Toolset (Windows only)
        if: runner.os == 'Windows'
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install wixtoolset

      - name: Build App (Linux)
        if: runner.os == 'Linux'
        run: pnpm run build:linux
        env:
          GITHUB_TOKEN: ${{ secrets.ELECTRON_BUILD_TOKEN }}

      - name: Build App (macOS)
        if: runner.os == 'macOS'
        run: pnpm run build:mac
        env:
          GITHUB_TOKEN: ${{ secrets.ELECTRON_BUILD_TOKEN }}

      - name: Build App (Windows)
        if: runner.os == 'Windows'
        run: pnpm run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.ELECTRON_BUILD_TOKEN }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: electron-app-${{ matrix.os }}
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          name: Electron App ${{ matrix.os }}
          tag_name: ${{ steps.tag.outputs.tag }}
